name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check project structure
      run: |
        test -d Models && test -d Scripts && test -d Plots && echo "✓ Project structure valid"